function reloadPage(){window.location.reload()}function isPageFresh(){return!0}function getNamespacedEventName(a){return NAMESPACE+"-"+a}
function renderOverlay(a,b){var c=window[NAMESPACE].overlays[b];c||(c=window[NAMESPACE].overlays[b]=document.createElement("div"),document.body.appendChild(c),c.style.position="absolute",c.style.backgroundColor="rgba(255, 64, 129, 0.5)",c.style.pointerEvents="none",c.style.zIndex=2147483647);c.style.left=a.left+window.scrollX+"px";c.style.top=a.top+window.scrollY+"px";c.style.height=a.height+"px";c.style.width=a.width+"px";c.style.visibility="visible"}
function hideOverlays(a){for(var b=window[NAMESPACE].overlays,c=b.length-1;c>=a;c--)b[c].style.visibility="hidden"}function highlight(a){a=window[NAMESPACE].DOMCache[a];if(window[NAMESPACE].highlightedElement!=a){window[NAMESPACE].highlightedElement=a;a=a.getClientRects();for(var b=0,c;c=a[b];b++)window[NAMESPACE].renderOverlay(c,b);window[NAMESPACE].hideOverlays(a.length)}}
function unhighlight(a){window[NAMESPACE].highlightedElement==window[NAMESPACE].DOMCache[a]&&(window[NAMESPACE].highlightedElement=null,window[NAMESPACE].hideOverlays(0))}function scrollIntoView(a){a in window[NAMESPACE].DOMCache&&window[NAMESPACE].DOMCache[a].scrollIntoView()}
function setBreakpoint(a,b){var c=window[NAMESPACE].resolveObject(a,b);b=window[NAMESPACE].getPropPath(a,b).pop();"function"===typeof c&&(a in window[NAMESPACE].breakPointIndices||(window[NAMESPACE].breakPointIndices[a]={}),window[NAMESPACE].breakPointIndices[a][b]=!0,debug(c))}
function clearBreakpoint(a,b){var c=window[NAMESPACE].resolveObject(a,b);b=window[NAMESPACE].getPropPath(a,b).pop();"function"===typeof c&&(a in window[NAMESPACE].breakPointIndices&&b in window[NAMESPACE].breakPointIndices[a]&&delete window[NAMESPACE].breakPointIndices[a][b],undebug(c))}function getPropPath(a,b,c){var d=[],e=c?window[NAMESPACE].modelIndexToPropMap[a]:window[NAMESPACE].indexToPropMap[a];b.forEach(function(g){e=e[g];d.push(e.__name__)});return d}
function resolveObject(a,b,c){var d=c?window[NAMESPACE].DOMModelCache[a]:window[NAMESPACE].DOMCache[a];window[NAMESPACE].getPropPath(a,b,c).forEach(function(e){d=d[e]});return d}function changeProperty(a,b,c,d){var e=window[NAMESPACE].getPropPath(a,b,d).pop();b.pop();(a=window[NAMESPACE].resolveObject(a,b,d))&&(a[e]=c)}
function getProperty(a,b,c){var d=window[NAMESPACE].getPropPath(a,b,c).pop();b.pop();a=window[NAMESPACE].resolveObject(a,b,c);return window[NAMESPACE].JSONizer.JSONizeProperty(d,a)}function addToCache(a,b){"TEMPLATE"===a.tagName&&a.model?window[NAMESPACE].DOMModelCache[b]=a.model:a.templateInstance&&(window[NAMESPACE].DOMModelCache[b]=a.templateInstance.model);window[NAMESPACE].DOMCache[b]=a}
function inspectorSelectionChangeListener(){$0.__keyPolymer__&&window.dispatchEvent(new CustomEvent(window[NAMESPACE].getNamespacedEventName("inspected-element-changed"),{detail:{key:$0.__keyPolymer__}}))}function getIndexMapObject(a,b,c){a=c?window[NAMESPACE].modelIndexToPropMap[a]:window[NAMESPACE].indexToPropMap[a];for(c=0;c<b.length;c++)a=a[b[c]];return a}
function addToSubIndexMap(a,b){a.__lastIndex__="__lastIndex__"in a?a.__lastIndex__+1:0;a[a.__lastIndex__]={__name__:b};a["name-"+b]=a.__lastIndex__}function removeFromSubIndexMap(a,b){var c=a[b].__name__;for(b+=1;b<=a.__lastIndex__;b++)a[b-1]=a[b];delete a["name-"+c];delete a[a.__lastIndex__--]}
function emptySubIndexMap(a,b,c){var d=c?window[NAMESPACE].modelIndexToPropMap:window[NAMESPACE].indexToPropMap;c=d[a];var e=b.pop();if(e){for(a=0;a<b.length;a++)c=c[b[a]];c[e]={__name__:c[e].__name__};c[e].__lastIndex__=-1}else d[a]={},d[a].__lastIndex__=-1}function isPolymerElement(a){return a&&"element"in a&&"polymer-element"===a.element.localName}function isCustomElement(a){return-1!==a.localName.indexOf("-")||a.getAttribute("is")}
function isUnregisteredCustomElement(a){return window[NAMESPACE].isCustomElement(a)&&a.constructor===HTMLElement}function warnUnregisteredCustomElement(a){console.log("%cThis custom element isn't registered: ","color: red; font-size: 13px;");console.log(a)}function filterProperty(a){return"_"!==a[0]&&"_"!==a.slice(-1)&&!filterProperty.blacklist[a]}
function setBlacklist(){window[NAMESPACE].filterProperty.blacklist={accessKey:!0,align:!0,attributes:!0,baseURI:!0,childElementCount:!0,childNodes:!0,children:!0,classList:!0,className:!0,clientHeight:!0,clientLeft:!0,clientTop:!0,clientWidth:!0,contentEditable:!0,dataset:!0,dir:!0,draggable:!0,firstChild:!0,firstElementChild:!0,hidden:!0,id:!0,innerHTML:!0,innerText:!0,inputMethodContext:!0,isContentEditable:!0,lang:!0,lastChild:!0,lastElementChild:!0,localName:!0,namespaceURI:!0,nextElementSibling:!0,
nextSibling:!0,nodeName:!0,nodeType:!0,nodeValue:!0,offsetHeight:!0,offsetLeft:!0,offsetParent:!0,offsetTop:!0,offsetWidth:!0,onabort:!0,onbeforecopy:!0,onbeforecut:!0,onbeforepaste:!0,onblur:!0,oncancel:!0,oncanplay:!0,oncanplaythrough:!0,onchange:!0,onclick:!0,onclose:!0,oncontextmenu:!0,oncopy:!0,oncuechange:!0,oncut:!0,ondblclick:!0,ondrag:!0,ondragend:!0,ondragenter:!0,ondragleave:!0,ondragover:!0,ondragstart:!0,ondrop:!0,ondurationchange:!0,onemptied:!0,onended:!0,onerror:!0,onfocus:!0,oninput:!0,
oninvalid:!0,onkeydown:!0,onkeypress:!0,onkeyup:!0,onload:!0,onloadeddata:!0,onloadedmetadata:!0,onloadstart:!0,onmousedown:!0,onmouseenter:!0,onmouseleave:!0,onmousemove:!0,onmouseout:!0,onmouseover:!0,onmouseup:!0,onmousewheel:!0,onpaste:!0,onpause:!0,onplay:!0,onplaying:!0,onprogress:!0,onratechange:!0,onreset:!0,onresize:!0,onscroll:!0,onsearch:!0,onseeked:!0,onseeking:!0,onselect:!0,onselectstart:!0,onshow:!0,onstalled:!0,onsubmit:!0,onsuspend:!0,ontimeupdate:!0,onvolumechange:!0,onwaiting:!0,
onwebkitfullscreenchange:!0,onwebkitfullscreenerror:!0,onwheel:!0,outerHTML:!0,outerText:!0,ownerDocument:!0,parentElement:!0,parentNode:!0,prefix:!0,previousElementSibling:!0,previousSibling:!0,scrollHeight:!0,scrollLeft:!0,scrollTop:!0,scrollWidth:!0,shadowRoot:!0,spellcheck:!0,style:!0,tabIndex:!0,tagName:!0,textContent:!0,title:!0,translate:!0,webkitShadowRoot:!0,webkitdropzone:!0,resolvePath:!0,shadowRoots:!0,$:!0,controller:!0,eventDelegates:!0,reflect:!0,onautocomplete:!0,onautocompleteerror:!0,
ontoggle:!0,hasBeenAttached:!0,element:!0}}function processMutations(a){for(var b={},c=[],d=0;d<a.length;d++){var e=a[d];"childList"===e.type&&(e=e.target,e.host&&(e=e.host),e.__keyPolymer__ in b||(c.push(window[NAMESPACE].getDOMJSON(e)),b[e.__keyPolymer__]=!0))}return c}
function getDOMJSON(a){return{data:window[NAMESPACE].JSONizer.JSONizeDOMObject(a||document.body,function(b,c,d){if(!b.__keyPolymer__){d?c.unRendered=!0:window[NAMESPACE].isPolymerElement(b)&&!b.shadowRoot&&(c.noShadowRoot=!0);window[NAMESPACE].lastDOMKey++;d=window[NAMESPACE].lastDOMKey;window[NAMESPACE].addToCache(b,d);window[NAMESPACE].indexToPropMap[d]={};window[NAMESPACE].modelIndexToPropMap[d]={};b.__keyPolymer__=d;if(d===window[NAMESPACE].firstDOMKey||b.shadowRoot){var e=new MutationObserver(function(h){window.dispatchEvent(new CustomEvent(window[NAMESPACE].getNamespacedEventName("dom-mutation"),
{detail:window[NAMESPACE].processMutations(h)}))});window[NAMESPACE].mutationObserverCache[d]=e;var g={childList:!0,subtree:!0};d===window[NAMESPACE].firstDOMKey&&e.observe(b,g);b.shadowRoot&&e.observe(b.shadowRoot,g)}window[NAMESPACE].isUnregisteredCustomElement(b)&&window[NAMESPACE].warnUnregisteredCustomElement(b)}c.key=b.__keyPolymer__;d=window[NAMESPACE].isPolymerElement(b);b.parentNode&&(c.parentKey=b.parentNode.host&&"object"===typeof b.parentNode.host?b.parentNode.host.__keyPolymer__:b.parentNode.__keyPolymer__);
d&&(c.isPolymer=!0,c.sourceURL=b.element.ownerDocument.URL)})}}
function getObjectJSON(a,b,c){var d=window[NAMESPACE].resolveObject(a,b,c);if(!d)return{data:JSON.stringify({value:[]})};var e=window[NAMESPACE].getIndexMapObject(a,b,c),g=null;0===b.length&&(g=function(h){return"__keyPolymer__"!==h});window[NAMESPACE].isPolymerElement(d)&&(g=function(h){return window[NAMESPACE].filterProperty(h)&&"__keyPolymer__"!==h});return{data:window[NAMESPACE].JSONizer.JSONizeObject(d,function(h){for(var f=h.value,l=0;l<f.length;l++)!c&&0===b.length&&a in window[NAMESPACE].breakPointIndices&&
f[l].name in window[NAMESPACE].breakPointIndices[a]&&(h.value[l].setBreakpoint=!0),window[NAMESPACE].addToSubIndexMap(e,f[l].name,c)},g)}}
function addObjectObserver(a,b,c){function d(q,p){for(p=p.__proto__;p;){if(p.hasOwnProperty(q))return!0;p=p.__proto__}return!1}function e(q){for(var p=window,n=p.dispatchEvent,r=CustomEvent,x=window[NAMESPACE].getNamespacedEventName("object-changed"),w={isModel:c,path:b,key:a,changes:[]},v=0;v<q.length;v++){var k=q[v],t={index:h["name-"+k.name],type:k.type,name:k.name},m;if(!(m=k.object===g)){a:{m=k.name;for(var y=k.obj,u=g;u!==y&&u;){if(u.hasOwnProperty(m)){m=!0;break a}u=u.__proto__}m=!1}m=!m}if(m){switch(k.type){case "update":if(window[NAMESPACE].isPolymerElement(g)&&
!window[NAMESPACE].filterProperty(k.name))continue;m={value:k.object[k.name]};t.object=window[NAMESPACE].JSONizer.JSONizeObject(m);break;case "delete":d(k.name,g)?(t.type="update",m={value:k.object[k.name]},t.object=window[NAMESPACE].JSONizer.JSONizeObject(m)):window[NAMESPACE].removeFromSubIndexMap(h,h["name-"+k.name],c);break;case "add":if(window[NAMESPACE].isPolymerElement(g)&&!window[NAMESPACE].filterProperty(k.name))continue;m={value:k.object[k.name]};t.object=window[NAMESPACE].JSONizer.JSONizeObject(m);
window[NAMESPACE].isPolymerElement(g)&&d(k.name,g)?t.type="update":window[NAMESPACE].addToSubIndexMap(h,k.name,c)}w.changes.push(t)}}n.call(p,new r(x,{detail:w}))}var g=window[NAMESPACE].resolveObject(a,b,c);if(g){var h=window[NAMESPACE].getIndexMapObject(a,b,c);Object.observe(g,e);for(var f=g.__proto__;f&&!Polymer.isBase(f);)Object.observe(f,e),f=f.__proto__;f=c?window[NAMESPACE].modelObserverCache:window[NAMESPACE].observerCache;f[a]||(f[a]={});f=f[a];for(var l=0;l<b.length;l++)f[b[l]]||(f[b[l]]=
{}),f=f[b[l]];f.__objectObserver__=e}}
function removeObjectObserver(a,b,c){function d(l,q,p){if(q.__objectObserver__){Object.unobserve(l,q.__objectObserver__);if(window[NAMESPACE].isPolymerElement(l))for(var n=l.__proto__;n&&!Polymer.isBase(n);)Object.unobserve(n,q.__objectObserver__),n=n.__proto__;n=Object.keys(q);for(var r=0;r<n.length;r++)"__objectObserver__"!==n[r]&&d(l[p[n[r]].__name__],q[n[r]],p[n[r]])}}var e=window[NAMESPACE].resolveObject(a,b,c);if(e){var g=c?window[NAMESPACE].modelObserverCache:window[NAMESPACE].observerCache,
h=g[a];c=c?window[NAMESPACE].modelIndexToPropMap[a]:window[NAMESPACE].indexToPropMap[a];for(var f=0;f<b.length;f++)g=h,h=h[b[f]],c=c[b[f]];d(e,h,c);delete g[0===b.length?a:b[b.length-1]]}}
function createCache(){window[NAMESPACE].DOMCache={};window[NAMESPACE].DOMModelCache={};window[NAMESPACE].observerCache={};window[NAMESPACE].modelObserverCache={};window[NAMESPACE].breakPointIndices={};window[NAMESPACE].indexToPropMap={};window[NAMESPACE].modelIndexToPropMap={};window[NAMESPACE].firstDOMKey=1;window[NAMESPACE].lastDOMKey=window[NAMESPACE].firstDOMKey-1;window[NAMESPACE].mutationObserverCache={};window[NAMESPACE].JSONizer=new window[NAMESPACE].DOMJSONizer;window[NAMESPACE].overlays=
[]};
